### ISSUE TITLE
Resolving Docker Compose hostnames in environment variables

### ISSUE THREAD

**Issue by willcode4food** [CBarraford/docker-redx#2]
When I try using a docker-compse.yml file to specify environment variables, I'd like to use the hostname docker assigns when it builds the container via Compose's link directive.  Assuming the docker container I am linking to is called "redis"  when I specify 

environment:

```
    - REDIS_HOST="'redis'" 
```

I receive the following error when hitting the API at any endpoint

`{
  "message": "Error connecting to redis: no resolver defined to resolve \"'redis'\""
}`

**Comment by cbarraford** [comment]
this sounds like nginx is unable to do a DNS lookup for `redis`, which makes some sense as nginx doesn't use builtin dns resolution by default.

Give this a try and see if it helps
http://stackoverflow.com/questions/35744650/docker-network-nginx-resolver

**Comment by willcode4food** [comment]
Thanks for the insight.  Looks like a similar ticket is open in the compose [github repo](https://github.com/docker/compose/issues/3412)

**Comment by willcode4food** [comment]
After much research, I was able to resolve this by installing dnsmasq, launching the dnsmasq command within the entrypoint.bash script and add resolver 127.0.0.11 to the http clause within the nginx.conf.   I can resolve the hostnames now.
